System.ArgumentException: 'The ADO.NET provider with invariant name 'System.Data.SQLite' is either not registered in the machine or application config file, or could not be loaded. See the inner exception for details.' Inner exception: ArgumentException: Unable to find the requested .Net Framework Data Provider.  It may not be installed. IDKif it's some weird connection string formatting issue, or out of date packages for ef w/ asp.net web forms, since it's all OLD.